language: c

# Supply at least one RACKET_VERSION environment variable definition
# here. RACKET_VERSION is used by the install-racket.sh script
# (specifed below under before_install) to select the version of
# Racket to download and install.
#
# If you supply more than one, you can create multiple builds (a
# Travis-CI build matrix resulting in multiple builds). You can use
# this to test against multiple Racket versions.
env:
 - RACKET_VERSION=5.3.5
 - RACKET_VERSION=5.3.6
 - RACKET_VERSION=6.0
 - RACKET_VERSION=6.0.1
 - RACKET_VERSION=6.1
 - RACKET_VERSION=6.1.1
 - RACKET_VERSION=HEAD

before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash # pipe to bash not sh!

install:

before_script:

script:
 - cd ..   # Travis did a cd into the dir. Back up, for the next:
 - /usr/racket/bin/raco pkg install --deps search-auto --link sha
 - /usr/racket/bin/raco test -x -p sha

after_script:
